# Generated by Django 3.0.5 on 2020-12-08 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='Subscription_detail',
            new_name='subscription_detail',
        ),
    ]
