# Generated by Django 3.0.5 on 2020-12-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20201208_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='Subscription_name',
            field=models.CharField(default='Free', max_length=200),
            preserve_default=False,
        ),
    ]
