# Generated by Django 3.0.5 on 2020-12-08 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_id', models.IntegerField()),
                ('episode_name', models.CharField(max_length=255)),
                ('episode_description', models.TextField()),
                ('episode_length', models.TimeField()),
                ('episode_date', models.DateField()),
                ('episode_link', models.URLField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.Series')),
            ],
        ),
    ]
